-- Chapter 2:- Operators

INSERT INTO employee
(EMP_NO, E_NAME, JOB, MGR, HIR_DATE, SAL, DEPT_NO)
VALUES
(7902, 'FORD', 'ANALYST', 7566, '1981-12-03', 3000, 20),
(7934, 'MILLER', 'CLERK', 7782, '1982-01-23', 1300, 10);

-- IN Operator:-

SELECT * FROM employee WHERE DEPT_NO IN (10, 20);
SELECT * FROM employee WHERE JOB IN ('CLERK', 'ANALYST');


-- LIKE Operator:-

SELECT * FROM employee WHERE E_NAME LIKE 'S%';
SELECT * FROM employee WHERE E_NAME LIKE '%_LL_%';
SELECT * FROM employee WHERE E_NAME LIKE '%_E_';
SELECT * FROM employee WHERE E_NAME LIKE '___R%';
SELECT * FROM employee WHERE JOB LIKE '_____';
SELECT * FROM employee WHERE E_NAME LIKE '_____%';

-- BETWEEN Operator:-

SELECT * FROM employee WHERE SAL BETWEEN 800 AND 1100;

-- IS Operator:-

SELECT * FROM employee WHERE MGR IS null;


-- LOGICAL Operators:-


SELECT E_NAME FROM employee WHERE JOB = 'SALESMAN' AND DEPT_NO = 30;
SELECT E_NAME FROM employee WHERE JOB = 'SALESMAN' AND DEPT_NO = 30 AND SAL > 1500;
SELECT E_NAME FROM employee WHERE E_NAME LIKE 'S%' OR E_NAME LIKE 'A%';
SELECT * FROM employee WHERE DEPT_NO NOT IN (10 , 20);
SELECT * FROM employee WHERE E_NAME NOT LIKE 'S%';
SELECT * FROM employee WHERE MGR IS NOT NULL AND DEPT_NO = 30;
SELECT * FROM employee WHERE JOB NOT IN ('MANAGER', 'CLERK') AND DEPT_NO IN (10, 20) AND SAL BETWEEN 1000 AND 3000;
SELECT * FROM employee WHERE SAL NOT BETWEEN 1000 AND 2000 AND DEPT_NO IN (10, 20, 30) AND JOB != 'SALESMAN';
SELECT * FROM employee WHERE E_NAME LIKE '%O%';

-- SORTING:-

SELECT * FROM employee ORDER BY SAL ASC;
SELECT * FROM employee ORDER BY SAL DESC;
